### ISSUE TITLE
Improvement In Content

### ISSUE THREAD

**Issue by abdulvasay-234** [LIEThyd/hacktober-sample#1]
- Keep the alignment equal (fill the right-side space)

<img width="320" alt="image" src="https://github.com/LIEThyd/hacktober-sample/assets/100799939/07700c4d-0815-4ce8-840c-ba0759a12d3b">

---

- **The first Paragraph should contain about CodeWave Hub**
ADD the following Text:

CodeWave Hub is an open-source chapter at Lords Institute of Engineering & Technology that nurtures student's interest in technology. It operates as a hobby and interest club, a platform where students can participate and contribute according to their passions.

This collaborative community brings together students who share similar technological interests, allowing them to work collectively on projects. Moreover, the community facilitates mentorship from experienced professionals, providing valuable guidance and insight.

---

- **Replace the following text with:**

**Details:**
Hacktoberfest is an annual event that encourages people to contribute to open source throughout october. Hacktoberfest is all about giving back to those projects, sharpening skills, and celebrating all things open source, especially the people that make open source so special. Thousands of people—coders and non-coders alike—have participated in hacktoberfest to support the projects they use and love, learn and practice skills that will enhance their careers, and meet new people who love open source as much as they do.

<img width="732" alt="image" src="https://github.com/LIEThyd/hacktober-sample/assets/100799939/48b9a48e-0134-4c11-a86d-fc35710ec7c0">

---

- Time: 10:00 AM IST Onwards on 17-1023 Ends on 4:00 PM IST on 18-10-23
**Adding India Standard Time**

---

- **Location: Hybrid, & then Lords name**

----
<img width="841" alt="image" src="https://github.com/LIEThyd/hacktober-sample/assets/100799939/300ee137-7f21-4486-84f7-237234e77d4b">

- **Add Social Media accounts in the blank space; GitHub & LinkedIn.**
---

- 4 line is repeated, replace it with **"Collaborate with fellow tech enthusiasts"**
<img width="344" alt="image" src="https://github.com/LIEThyd/hacktober-sample/assets/100799939/ac0a800f-b604-4e07-a9fe-8e7811fed369">

---

- Replace the text and write **"Join CodeWave: HacktoberFest 2023 Edition, by Filling the form below:"**
<img width="669" alt="image" src="https://github.com/LIEThyd/hacktober-sample/assets/100799939/731d3e88-4283-4be4-98c8-e5f153ef5e2d">

---

**Correction:**
CodeWave Hub: HacktoberFest 2023 Edition

<img width="674" alt="image" src="https://github.com/LIEThyd/hacktober-sample/assets/100799939/edcd9fe2-a3ee-411c-861a-48b058afd9dd">

---

- Replace the text with:

**Low or no-code contributions**
Contributing to open source isn’t just for technical folks who want to write code. There are lots of opportunities to use your professional skills in support of open-source projects.  We’re making a point to encourage contributions that require some technical experience or none at all. No matter your experience, you can participate in hacktoberfest!
Hacktoberfest welcomes people of any experience level to participate, and low-code and non-code contributions are fantastic choices for folks who don’t have a lot of technical knowledge.
Happy hacking!

<img width="697" alt="image" src="https://github.com/LIEThyd/hacktober-sample/assets/100799939/e9bfd57a-f304-4f28-961e-dcc48ae469c7">

**Comment by bhalerao-2002** [comment]
Hello, I have read all the issues and Assure you that I will solve them all with ease.
Please assign me this issue, Under Hacktober 2023

**Comment by abdulvasay-234** [comment]
I appreciate your enthusiasm for contributing to the development of the site, but we have resolved all the issues.
Feel free to check the latest website and raise an issue if there is anything you can add up (or) improve. https://github.com/LIEThyd/Codewave-site
